### ISSUE TITLE
vizer.tv

### ISSUE THREAD

**Issue by xitero** [NanoAdblocker/NanoCore#142]
### Describe the issue (Required)
I can not click on any button on the site, either to search or to log into my account. When I click, I'm redirected to the following link: `http://udriveme2.com/show?bver=1&refer=http%3A%2F%2Fvizer.tv%2F&kw=%5B%22vizer%22%2C%22tv%22%2C%22-%22%2C%22assistir%22%2C%22filmes%22%2C%22e%22%2C%22s%C3%A9ries%22%2C%22online%22%2C%22hd%22%5D&key=50ebb83f8c66e52e9767a508f92d5dad&scrWidth=1920&scrHeight=1080&tz=-3&ship=&pst=&res=4.31&dev=r&psid=var2_f`

After pressing F5 a few times, the problem is resolved and I can access other pages from that same site normally. However, the problem returns some time later during the use of the site. When I use Adblock Plus, this problem does not occur. The only relation to this I found was the following link where the specified domain above is on this list:
```
||udriveme2.com^$third-party
https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt
```

### Screenshots (Required)
https://prnt.sc/iwawuv (Look at the image on the lower left side)

### Screenshot of console (Required, press `F12` to open the console)
http://prntscr.com/iwb230
https://prnt.sc/iwb113

### URLs where this issue occurs (Required if applicable)
http://vizer.tv/

### Reproduction Steps (Optional if trivial)
Just open the site, close the screen asking to enjoy facebook and wait a few seconds and then try clicking on any area of the site.

#### Environment (Required)

- Operating System and Version: Windows 10 1709 16299.309
- Browser and Version: Google Chrome 65.0.3325.181 64 bits
- Nano Adblocker Version: 1.0.0.37
- Nano Defender Version: 13.49

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Portuguese.
Can you reproduce?
I do not get any popups or redirections, I do get an anti-adblock message.

![unbenannt](https://user-images.githubusercontent.com/16838044/37882204-71e859ea-30a1-11e8-9588-70e0629bc436.JPG)

Which is fixed by `@@||vizer.tv^$generichide`

**Comment by KonoromiHimaries** [comment]
![2018-03-26-vizer tv - assistir filmes e series online hd](https://user-images.githubusercontent.com/5884000/37882295-69c4bf32-30a2-11e8-95e6-709af4b0d0b8.png)

**Comment by okiehsch** [comment]
OK, after deleting cookies and reloading I can reproduce the redirection.
````
@@||vizer.tv^$generichide
vizer.tv##script:inject(addEventListener-defuser.js, /^(click|mousedown|mousemove|touchstart|touchend|touchmove)/, system.popunder)
vizer.tv##script:inject(setInterval-defuser.js, system.popunder, 500)
`````
fixes the issues on my end.

**Comment by KonoromiHimaries** [comment]
@okiehsch not fixed on my end
![2018-03-26-assistir paddington 2 online](https://user-images.githubusercontent.com/5884000/37882655-86e1710c-30a5-11e8-84b6-cb6f4d389dac.png)
`http://vizer.tv/assistir/filme/paddington-2/online-gratis`

**Comment by KonoromiHimaries** [comment]
@okiehsch after deleting cookies and reloading I still have a anty-adblock alert
![2018-03-26-vizer tv - assistir filmes e series online hd](https://user-images.githubusercontent.com/5884000/37882295-69c4bf32-30a2-11e8-95e6-709af4b0d0b8.png)

**Comment by KonoromiHimaries** [comment]
@okiehsch after update ublock filters, deleting cookies and reloading site I still have anti-adblock

![2018-03-26-assistir paddington 2 online](https://user-images.githubusercontent.com/5884000/37882902-552b2eb2-30a7-11e8-9b94-f1929b9dd138.png)
`http://vizer.tv/assistir/filme/paddington-2/online-gratis`

to reproduce open link and select the movie

**Comment by KonoromiHimaries** [comment]
@okiehsch after update ublock filters, deleting cookies and reloading site I still have anti-adblock

![2018-03-26-assistir paddington 2 online](https://user-images.githubusercontent.com/5884000/37882902-552b2eb2-30a7-11e8-9b94-f1929b9dd138.png)
`http://vizer.tv/assistir/filme/paddington-2/online-gratis`

to reproduced:
- open link 
- chose movie

**Comment by okiehsch** [comment]
I can't reproduce. I can selext the movie and it plays fine.
![unbenannt](https://user-images.githubusercontent.com/16838044/37882994-1c28260a-30a8-11e8-9652-709b0753e11d.JPG)

**Comment by KonoromiHimaries** [comment]
example click this
![37882902-552b2eb2-30a7-11e8-9b94-f1929b9dd138](https://user-images.githubusercontent.com/5884000/37883035-76ea1148-30a8-11e8-848b-e5a6167ac79f.png)
`http://vizer.tv/assistir/filme/paddington-2/online-gratis`

**Comment by KonoromiHimaries** [comment]
once it's detected, anti-adblock works everywhere
![2018-03-26-vizer tv - assistir filmes e series online hd](https://user-images.githubusercontent.com/5884000/37882295-69c4bf32-30a2-11e8-95e6-709af4b0d0b8.png)

**Comment by okiehsch** [comment]
![unbenannt](https://user-images.githubusercontent.com/16838044/37883166-17039af0-30a9-11e8-8723-a33acd311aa8.JPG)

I can't reproduce, what happens if you click close/fechar?
Can you access and watch the videos?

**Comment by KonoromiHimaries** [comment]
@okiehsch popups and ads

**Comment by okiehsch** [comment]
What kind of popups, i.e. what does your logger show?

**Comment by KonoromiHimaries** [comment]
`https://gist.github.com/KonoromiHimaries/b64d4aaef099a7a964fe6a73099da06d`
![2018-03-26-developer tools - http___vizer tv_home](https://user-images.githubusercontent.com/5884000/37883472-e58182b0-30aa-11e8-8f75-c8ed249b865e.png)

**Comment by KonoromiHimaries** [comment]
@okiehsch ohh.. I know why you not can to reproduce,

to reproduce
- join to `vizer.tv`
- delete cookie and click ctrl+f5
- in right mouse button click the example `paddington 2 movie` and click open in new card
- them click anything, exapmle
![37882902-552b2eb2-30a7-11e8-9b94-f1929b9dd138](https://user-images.githubusercontent.com/5884000/37883035-76ea1148-30a8-11e8-848b-e5a6167ac79f.png)

**Comment by okiehsch** [comment]
Nope, I still can't reproduce, but I can see `vizerNewBox` in the source.

Does
`vizer.tv##.open.adsByVizer.vizerNewBox`
work for you.

**Comment by KonoromiHimaries** [comment]
yea, it seems to works

**Comment by okiehsch** [comment]
OK, you can simply click that message away, so that is an annoyance, which I won't fix in `uBO-filters`.

Regarding the popups, 
````
vizer.tv##script:inject(addEventListener-defuser.js, /^(click|mousedown|mousemove|touchstart|touchend|touchmove)/, system.popunder)
vizer.tv##script:inject(abort-on-property-write.js, Fingerprint2)
vizer.tv##script:inject(setInterval-defuser.js, system.popunder, 500)
````
fixes all popups on my end, so I can't reproduce.

**Comment by xitero** [comment]
I have already done the indicated procedures and still have the problem of trying to click anywhere on the site, be redirected to the following link in a new tab: http://udriveme2.com/show?bver=1&refer=http%3A% 2F% 2Fvizer.tv% 2F & kw =% 5B% 22w% 22% 2C% 22tv% 22% 2C% 22-% 22% 2C% 22watch% 22% 2C% 22films% 22% 2C% 22e% 22% C3% A9ries% 22% 2C% 22online% 22% 2C% 22hd% 22% 5D & key = 50ebb83f8c66e52e9767a508f92d5dad & scrWidth = 1920 & scrHeight = 1080 & tz = -3 & ship = & pst = & res = 4.31 & dev = r & psid = var2_f

Then this link redirects me to some random site.

**Comment by jspenguin2017** [comment]
Can you supply a proper test link?
